version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: univ_app
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - app-bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db-data:
  app-bundle: