default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db # # docker-compose.ymlのservice名
  username: univ_app
  password: password  # docker-compose.ymlのPOSTGRES_PASSWORD

development:
  <<: *default
  database: university_app_development

test:
  <<: *default
  database: university_app_test

production:
  <<: *default
  database: university_app_production
  username: university_app
  password: <%= ENV['UNIVERSITY_APP_DATABASE_PASSWORD'] %>
