name: rails

# 実行タイミング
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 実行内容
jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rubocop
        uses: reviewdog/action-rubocop@v1