name: rails

# 実行タイミング
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 実行内容
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Run rubocop
        run: bundle exec rubocop
