name: rails

# 実行タイミング
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 実行内容
jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Build and setup
        run: |
          bundle update rails
          gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
          bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop
